apiVersion: apps/v1
kind: Deployment
metadata:
  name: safebank-webapp-deployment
  labels:
    app: safebank-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: safebank-webapp
  template:
    metadata:
      labels:
        app: safebank-webapp
    spec:
      containers:
      - name: safebank-container
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80